apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=

# Opaque is the default type for arbitrary key-value pairs.
# Generate mongo-root-username by typing the below command in terminal: echo -n 'username' | base64
# Generate mongo-root-password by typing the below command in terminal: echo -n 'password' | base64